-- Adds workflow fields introduced after the original baseline. No records are removed.
ALTER TABLE material_transfers ADD COLUMN IF NOT EXISTS department TEXT;
ALTER TABLE material_transfers ADD COLUMN IF NOT EXISTS requested_by TEXT;
ALTER TABLE material_transfers ADD COLUMN IF NOT EXISTS requisition_id INTEGER REFERENCES requisitions(id) ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS idx_material_transfers_department ON material_transfers(department);
CREATE INDEX IF NOT EXISTS idx_material_transfers_requisition ON material_transfers(requisition_id);
ALTER TABLE disposals ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE disposals ADD COLUMN IF NOT EXISTS approved_by TEXT;
ALTER TABLE disposals ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP;
ALTER TABLE disposals ADD COLUMN IF NOT EXISTS executed_by TEXT;
ALTER TABLE disposals ADD COLUMN IF NOT EXISTS executed_at TIMESTAMP;
ALTER TABLE disposals ADD COLUMN IF NOT EXISTS disposal_date DATE;
ALTER TABLE disposals ADD COLUMN IF NOT EXISTS disposal_method TEXT;
ALTER TABLE disposals ADD COLUMN IF NOT EXISTS witness TEXT;
ALTER TABLE disposals ADD COLUMN IF NOT EXISTS supporting_document TEXT;
ALTER TABLE disposals ADD COLUMN IF NOT EXISTS assessment_result TEXT;
ALTER TABLE disposals ADD COLUMN IF NOT EXISTS assessment_notes TEXT;
ALTER TABLE disposals ADD COLUMN IF NOT EXISTS reviewed_by TEXT;
ALTER TABLE disposals ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMP;
ALTER TABLE disposals ADD COLUMN IF NOT EXISTS confirmed_by TEXT;
ALTER TABLE disposals ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMP;
ALTER TABLE disposals ADD COLUMN IF NOT EXISTS posted_by TEXT;
ALTER TABLE disposals ADD COLUMN IF NOT EXISTS posted_at TIMESTAMP;
ALTER TABLE user_cards ADD COLUMN IF NOT EXISTS user_id INTEGER REFERENCES users(id) ON DELETE RESTRICT;
UPDATE user_cards uc SET user_id = u.id FROM users u WHERE uc.user_id IS NULL AND uc.user_name = u.name;
CREATE INDEX IF NOT EXISTS idx_user_cards_user ON user_cards(user_id);
ALTER TABLE stock_taking_sessions ADD COLUMN IF NOT EXISTS assigned_to TEXT;
ALTER TABLE stock_taking_sessions ADD COLUMN IF NOT EXISTS assigned_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
UPDATE stock_taking_sessions st SET assigned_user_id = u.id FROM users u WHERE st.assigned_user_id IS NULL AND st.assigned_to = u.name AND u.role = 'Stock Clerk';
ALTER TABLE stock_taking_items ADD COLUMN IF NOT EXISTS recount_physical_qty NUMERIC(14,2);
ALTER TABLE stock_taking_items ADD COLUMN IF NOT EXISTS recount_variance NUMERIC(14,2);
ALTER TABLE stock_taking_items ADD COLUMN IF NOT EXISTS recounted_by TEXT;
ALTER TABLE stock_taking_items ADD COLUMN IF NOT EXISTS recounted_at TIMESTAMP;
CREATE INDEX IF NOT EXISTS idx_stock_taking_assigned_to ON stock_taking_sessions(assigned_to);
CREATE INDEX IF NOT EXISTS idx_stock_taking_assigned_user ON stock_taking_sessions(assigned_user_id);
CREATE INDEX IF NOT EXISTS idx_stock_taking_status ON stock_taking_sessions(status);
CREATE INDEX IF NOT EXISTS idx_stock_taking_items_session ON stock_taking_items(session_id);
